#!/bin/bash

read -r max < /sys/class/backlight/intel_backlight/max_brightness
((step = max / 10))
file=/sys/class/backlight/intel_backlight/brightness

case "$1" in
    -i|--increase) ((val = +step));;
    -d|--decrease) ((val = -step));;
esac

if !((val)); then
    echo "Increase or decrease screen brightness"
    echo "Usage: ${0##*/} --increase | --decrease"
    exit
fi

read -r cur < "$file"
((val = cur + val))

if ((val <   0)); then ((val =   0)); fi
if ((val > max)); then ((val = max)); fi

printf '%d' "$val" > "$file"

printf 'Before: %3d\n' "$cur"
printf 'After : %3d\n' "$val"
